name: Deploy to Kubernetes

on: [push]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-hello-world:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/nodejs-hello-world:latest ${{ secrets.DOCKER_USERNAME }}/nodejs-hello-world:v1
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-hello-world:v1

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/nodejs-hello-world || exit 1

      - name: Rollback if deployment fails
        if: failure()
        run: kubectl rollout undo deployment/nodejs-hello world
